language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "bramhi123-github"
    token:
      secure: "b1ddfbcc72a149e9ef8de2ab1aab91f6f2ca014a"

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'


